import { Avatar } from "@prisma/client";

export const AVATAR_URL: Record<Avatar, string> = {
	ant: "/assets/avatar/ant.png",
	bee: "/assets/avatar/bee.png",
	butterfly: "/assets/avatar/butterfly.png",
	cat: "/assets/avatar/cat.png",
	cow: "/assets/avatar/cow.png",
	dog: "/assets/avatar/dog.png",
	dragonfly: "/assets/avatar/dragonfly.png",
	duck: "/assets/avatar/duck.png",
	elephant: "/assets/avatar/elephant.png",
	fly: "/assets/avatar/fly.png",
	fox: "/assets/avatar/fox.png",
	frog: "/assets/avatar/frog.png",
	giraffe: "/assets/avatar/giraffe.png",
	hippo: "/assets/avatar/hippo.png",
	horse: "/assets/avatar/horse.png",
	leopard: "/assets/avatar/leopard.png",
	monkey: "/assets/avatar/monkey.png",
	mouse: "/assets/avatar/mouse.png",
	octopus: "/assets/avatar/octopus.png",
	owl: "/assets/avatar/owl.png",
	panda: "/assets/avatar/panda.png",
	placeholder: "/assets/avatar/placeholder.png",
	quail: "/assets/avatar/quail.png",
	rabbit: "/assets/avatar/rabbit.png",
	shark: "/assets/avatar/shark.png",
	sheep: "/assets/avatar/sheep.png",
	spider: "/assets/avatar/spider.png",
	tiger: "/assets/avatar/tiger.png",
	whale: "/assets/avatar/whale.png",
	wolf: "/assets/avatar/wolf.png",
	zebra: "/assets/avatar/zebra.png",
};
